[pytest]
pythonpath = .
testpaths =
    pruebas_postgresql
    aplicacion/nucleo/pruebas
    tests/test_generador_cliente_openapi.py
    tests/test_integracion_continua.py
    tests/test_verificar_arquitectura.py
    tests/test_codigo_qr_carnet.py
    tests/test_operacion_comedor.py
    tests/test_operacion_qr_carnet.py
    tests/test_tiempo.py
    tests/test_validar_alembic_docker.py
