"""Puertos y fachada de persistencia del comedor."""

from datetime import date
from typing import Protocol

from aplicacion.nucleo.base_datos import FabricaConexionSql

from .repositorio_catalogo import RepositorioSqlCatalogoComedor
from .repositorio_operacion import RepositorioSqlOperacionComedor
from .repositorio_operacion_consultas import RepositorioSqlConsultasOperacion


class RepositorioComedor(Protocol):
    def personas(
        self, tipo_persona: str | None = None, incluir_inactivas: bool = False
    ) -> list[dict]: ...
    def persona(self, id_persona: int) -> dict: ...
    def persona_por_estudiante(self, id_estudiante: int) -> int: ...
    def persona_por_usuario(self, id_usuario: int) -> dict: ...
    def reserva_por_persona_fecha(self, id_persona: int, fecha: date) -> dict | None: ...
    def crear_profesor(self, id_usuario: int, nombre: str, colegio: str | None) -> dict: ...
    def cuenta(self, id_persona: int) -> dict: ...
    def movimientos(self, id_persona: int, limite: int) -> list[dict]: ...
    def recargar(
        self, id_persona: int, cantidad: int, concepto: str | None, clave: str, usuario: int
    ) -> dict: ...
    def reservar(self, id_persona: int, fecha: date, usuario: int | None) -> dict: ...
    def cancelar(self, id_persona: int, fecha: date, usuario: int | None) -> dict: ...
    def ingresar(
        self, codigo_barras: str, fecha: date, usuario: int | None, terminal_id: str | None = None
    ) -> dict: ...
    def configuracion_operacion(self) -> dict: ...
    def historial_operacion(self, fecha: date, limite: int) -> list[dict]: ...
    def estado_operacion(self) -> dict: ...


class RepositorioSqlComedor(RepositorioSqlCatalogoComedor, RepositorioSqlOperacionComedor, RepositorioSqlConsultasOperacion):
    """Implementación única compuesta por capacidades especializadas."""

    def __init__(self, fabrica: FabricaConexionSql) -> None:
        RepositorioSqlCatalogoComedor.__init__(self, fabrica)
        RepositorioSqlOperacionComedor.__init__(self, fabrica)
