-- Almacenamiento local PostgreSQL de fotografías privadas de personas.
CREATE TABLE IF NOT EXISTS fotografia_persona (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    persona_id integer NOT NULL UNIQUE REFERENCES persona(id) ON DELETE CASCADE,
    contenido bytea NOT NULL,
    tipo_contenido varchar(80) NOT NULL CHECK (tipo_contenido IN ('image/jpeg', 'image/png'))
);

-- La API consulta y administra la foto; el usuario de migración puede recuperarla.
GRANT SELECT, INSERT, UPDATE, DELETE ON fotografia_persona TO scb_api, scb_migrador;
GRANT USAGE, SELECT ON SEQUENCE fotografia_persona_id_seq TO scb_api, scb_migrador;
