/** Generado por web/scripts/generar_cliente_openapi.py; no editar manualmente. */

import type { OperacionApi } from "../operaciones";

export const OPERACIONES_COMUNES: readonly OperacionApi[] = [
  {
    metodo: "GET",
    ruta: "/api/v1/anios-lectivos",
    operacionId: "anios_api_v1_anios_lectivos_get",
    dominio: "comunes",
  },
  {
    metodo: "POST",
    ruta: "/api/v1/anios-lectivos",
    operacionId: "crear_anio_api_v1_anios_lectivos_post",
    dominio: "comunes",
  },
  {
    metodo: "POST",
    ruta: "/api/v1/anios-lectivos/{anio_id}/activar",
    operacionId: "activar_api_v1_anios_lectivos__anio_id__activar_post",
    dominio: "comunes",
  },
  {
    metodo: "GET",
    ruta: "/api/v1/anios-lectivos/{anio_id}/secciones",
    operacionId: "secciones_anio_api_v1_anios_lectivos__anio_id__secciones_get",
    dominio: "comunes",
  },
  {
    metodo: "GET",
    ruta: "/api/v1/anios-lectivos/{anio_id}/secciones/{seccion}/resumen-pines",
    operacionId: "resumen_pines_seccion_api_v1_anios_lectivos__anio_id__secciones__seccion__resumen_pines_get",
    dominio: "comunes",
  },
  {
    metodo: "GET",
    ruta: "/api/v1/matriculas",
    operacionId: "matriculas_api_v1_matriculas_get",
    dominio: "comunes",
  },
  {
    metodo: "POST",
    ruta: "/api/v1/matriculas",
    operacionId: "crear_matricula_api_v1_matriculas_post",
    dominio: "comunes",
  },
  {
    metodo: "PUT",
    ruta: "/api/v1/matriculas/{matricula_id}/beneficio-comedor",
    operacionId: "actualizar_beneficio_comedor_api_v1_matriculas__matricula_id__beneficio_comedor_put",
    dominio: "comunes",
  },
  {
    metodo: "PUT",
    ruta: "/api/v1/matriculas/{matricula_id}/beneficios",
    operacionId: "actualizar_beneficios_api_v1_matriculas__matricula_id__beneficios_put",
    dominio: "comunes",
  },
  {
    metodo: "PUT",
    ruta: "/api/v1/matriculas/{matricula_id}/ruta",
    operacionId: "cambiar_ruta_matricula_api_v1_matriculas__matricula_id__ruta_put",
    dominio: "comunes",
  },
  {
    metodo: "GET",
    ruta: "/api/v1/parametros-operativos/horarios-reserva",
    operacionId: "horarios_reserva_api_v1_parametros_operativos_horarios_reserva_get",
    dominio: "comunes",
  },
  {
    metodo: "PUT",
    ruta: "/api/v1/parametros-operativos/horarios-reserva/{turno}",
    operacionId: "horario_reserva_api_v1_parametros_operativos_horarios_reserva__turno__put",
    dominio: "comunes",
  },
  {
    metodo: "GET",
    ruta: "/api/v1/parametros-operativos/institucion",
    operacionId: "institucion_api_v1_parametros_operativos_institucion_get",
    dominio: "comunes",
  },
  {
    metodo: "PUT",
    ruta: "/api/v1/parametros-operativos/institucion",
    operacionId: "actualizar_institucion_api_v1_parametros_operativos_institucion_put",
    dominio: "comunes",
  },
  {
    metodo: "GET",
    ruta: "/api/v1/personas",
    operacionId: "personas_api_v1_personas_get",
    dominio: "comunes",
  },
  {
    metodo: "POST",
    ruta: "/api/v1/personas",
    operacionId: "crear_persona_api_v1_personas_post",
    dominio: "comunes",
  },
  {
    metodo: "POST",
    ruta: "/api/v1/personas/pines/seccion",
    operacionId: "reiniciar_pines_seccion_api_v1_personas_pines_seccion_post",
    dominio: "comunes",
  },
  {
    metodo: "GET",
    ruta: "/api/v1/personas/referencias/{referencia_publica}",
    operacionId: "obtener_persona_referencia_publica_api_v1_personas_referencias__referencia_publica__get",
    dominio: "comunes",
  },
  {
    metodo: "GET",
    ruta: "/api/v1/personas/resumen",
    operacionId: "resumen_personas_api_v1_personas_resumen_get",
    dominio: "comunes",
  },
  {
    metodo: "GET",
    ruta: "/api/v1/personas/{persona_id}",
    operacionId: "obtener_persona_api_v1_personas__persona_id__get",
    dominio: "comunes",
  },
  {
    metodo: "PUT",
    ruta: "/api/v1/personas/{persona_id}",
    operacionId: "actualizar_persona_api_v1_personas__persona_id__put",
    dominio: "comunes",
  },
  {
    metodo: "POST",
    ruta: "/api/v1/personas/{persona_id}/desactivar",
    operacionId: "desactivar_persona_api_v1_personas__persona_id__desactivar_post",
    dominio: "comunes",
  },
  {
    metodo: "DELETE",
    ruta: "/api/v1/personas/{persona_id}/foto",
    operacionId: "eliminar_foto_api_v1_personas__persona_id__foto_delete",
    dominio: "comunes",
  },
  {
    metodo: "GET",
    ruta: "/api/v1/personas/{persona_id}/foto",
    operacionId: "consultar_foto_api_v1_personas__persona_id__foto_get",
    dominio: "comunes",
  },
  {
    metodo: "POST",
    ruta: "/api/v1/personas/{persona_id}/foto",
    operacionId: "cargar_foto_api_v1_personas__persona_id__foto_post",
    dominio: "comunes",
  },
  {
    metodo: "POST",
    ruta: "/api/v1/personas/{persona_id}/reiniciar-pin",
    operacionId: "reiniciar_pin_api_v1_personas__persona_id__reiniciar_pin_post",
    dominio: "comunes",
  },
  {
    metodo: "GET",
    ruta: "/api/v1/portal/carnet",
    operacionId: "carnet_api_v1_portal_carnet_get",
    dominio: "comunes",
  },
  {
    metodo: "GET",
    ruta: "/api/v1/portal/carnet/foto",
    operacionId: "foto_carnet_api_v1_portal_carnet_foto_get",
    dominio: "comunes",
  },
  {
    metodo: "GET",
    ruta: "/api/v1/portal/estado",
    operacionId: "estado_api_v1_portal_estado_get",
    dominio: "comunes",
  },
  {
    metodo: "GET",
    ruta: "/api/v1/rutas",
    operacionId: "rutas_api_v1_rutas_get",
    dominio: "comunes",
  },
  {
    metodo: "POST",
    ruta: "/api/v1/rutas",
    operacionId: "crear_ruta_api_v1_rutas_post",
    dominio: "comunes",
  },
  {
    metodo: "GET",
    ruta: "/api/v1/rutas/paleta",
    operacionId: "paleta_rutas_api_v1_rutas_paleta_get",
    dominio: "comunes",
  },
  {
    metodo: "PUT",
    ruta: "/api/v1/rutas/{ruta_id}",
    operacionId: "actualizar_ruta_api_v1_rutas__ruta_id__put",
    dominio: "comunes",
  },
  {
    metodo: "POST",
    ruta: "/api/v1/rutas/{ruta_id}/asignaciones",
    operacionId: "asignar_api_v1_rutas__ruta_id__asignaciones_post",
    dominio: "comunes",
  },
  {
    metodo: "GET",
    ruta: "/api/v1/tiquetes/personas",
    operacionId: "buscar_personas_venta_api_v1_tiquetes_personas_get",
    dominio: "comunes",
  },
  {
    metodo: "GET",
    ruta: "/api/v1/tiquetes/personas/{persona_id}/foto",
    operacionId: "foto_persona_venta_api_v1_tiquetes_personas__persona_id__foto_get",
    dominio: "comunes",
  },
  {
    metodo: "GET",
    ruta: "/api/v1/tiquetes/tarifas",
    operacionId: "tarifas_api_v1_tiquetes_tarifas_get",
    dominio: "comunes",
  },
  {
    metodo: "POST",
    ruta: "/api/v1/tiquetes/tarifas",
    operacionId: "tarifa_api_v1_tiquetes_tarifas_post",
    dominio: "comunes",
  },
  {
    metodo: "PUT",
    ruta: "/api/v1/tiquetes/tarifas/{tarifa_id}",
    operacionId: "actualizar_tarifa_api_v1_tiquetes_tarifas__tarifa_id__put",
    dominio: "comunes",
  },
  {
    metodo: "POST",
    ruta: "/api/v1/tiquetes/ventas",
    operacionId: "venta_api_v1_tiquetes_ventas_post",
    dominio: "comunes",
  },
] as const;
